chore: deploy workflow updates

diff --git a/.github/workflows/build-publish-lib.yml b/.github/workflows/build-publish-lib.yml
--- a/.github/workflows/build-publish-lib.yml
+++ b/.github/workflows/build-publish-lib.yml
@@ -1,12 +1,14 @@
 name: Build and Publish the Library
 on:
-  push:
-    tags:
-      - v*
+  workflow_dispatch
 
 jobs:
   build-and-deploy-lib:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+
     steps:
       - name: Checkout 🛎️
         uses: actions/checkout@v3
@@ -18,11 +20,33 @@ jobs:
           architecture: x64
           registry-url: "https://registry.npmjs.org"
 
-      - name: Install and Build 🔧
+      - name: Get version
+        id: package-version
+        uses: martinbeentjes/npm-get-version-action@v1.1.0
+
+      - name: Check tag does not exist yet
+        run: if git rev-list v${{ steps.package-version.outputs.current-version }}; then echo "Tag already exists. Aborting the release process."; exit 1; fi
+
+      - name: Tag commit and push
+        uses: mathieudutour/github-tag-action@v5.6
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          custom_tag: ${{ steps.package-version.outputs.current-version }}
+
+      - name: Install and link 🔗
         run: |
           npm ci
           npm link
           npm link @maplibre/maplibre-gl-directions
+
+      - name: Prepare release
+        id: prepare_release
+        run: |
+          echo ::set-output name=version_tag::v${{ steps.package-version.outputs.current-version }}
+          echo ::set-output name=release_type::$(node -e "console.log(require('semver').prerelease('${{ steps.package-version.outputs.current-version }}') ? 'prerelease' : 'regular')")
+
+      - name: Build 🔧
+        run: |
           npm run build
 
       - name: Deploy 🚀
